// src/registry/generateExternalAssetAdapters.js
//
// For each entry in externalAdapters.config.js: introspects the package's
// named exports, writes studio/assets/<assetType>/manifest.json (with a
// generated enum for the content key) and <assetType>.jsx (a thin wrapper
// around the library, built from the SAME sizeProp/colorProp/extraProps
// declared in the config — no per-library JSX hand-written).
//
// Run via `node src/registry/generateExternalAssetAdapters.js`, wired into
// `prebuild` ahead of generateRegistryManifest.js (the asset folders this
// writes must exist before the registry scanner runs). In CI, run it then
// `git diff --exit-code studio/assets/` — same staleness-catching pattern
// as registry.generated.json and TOON round-trips.
//
// Every file this writes is headed with a DO NOT EDIT banner; hand edits
// belong in externalAdapters.config.js, not in the generated output.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { EXTERNAL_ADAPTERS } from "./externalAdapters.config.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ASSETS_ROOT = path.join(__dirname, "../../studio/externalAssets"); // not studio/assets because those are hand-written

function toContentKey(exportName, strategy) {
  if (typeof strategy === "function") return strategy(exportName);
  if (strategy === "upperSnake") {
    return exportName.replace(/([a-z])([A-Z])/g, "$1_$2").toUpperCase();
  }
  return exportName; // "verbatim"
}

async function introspectExports(pkg) {
  const mod = await import(pkg);
  // Only keep entries that look like components: functions or objects
  // (forwardRef/memo wrap to objects), excluding the "default" slot unless
  // it's the only export (some packages ship a single default icon set
  // object keyed by name instead of one named export per icon).
  const names = Object.keys(mod).filter((k) => k !== "default");
  if (names.length > 0) return names;
  if (mod.default && typeof mod.default === "object") return Object.keys(mod.default);
  throw new Error(`generateExternalAssetAdapters: couldn't introspect any components from "${pkg}"`);
}

function buildManifest(adapter, exportNames) {
  const keyEnum = exportNames.map((n) => toContentKey(n, adapter.keyStrategy));
  const styleProps = {};
  for (const [propName, cfg] of Object.entries(adapter.extraProps ?? {})) {
    styleProps[cfg.styleKey] = { type: "string" };
  }
  if (adapter.colorProp) {
    styleProps.monoColorToken = { type: "string", description: "Style token or hex resolved and passed as the library's color prop." };
  }

  return {
    assetType: adapter.assetType,
    component: `${adapter.assetType}.jsx`,
    description:
      `${adapter.description} Generated from "${adapter.package}" — do not hand-edit; ` +
      `re-run generateExternalAssetAdapters.js after updating externalAdapters.config.js.` +
      (adapter.ssrSafe === "unverified"
        ? " SSR-safety unverified: confirm this package doesn't touch window/document at import time before relying on it in a real render."
        : ""),
    defaultSize: adapter.defaultSize,
    defaultStyle: Object.fromEntries(
      Object.values(adapter.extraProps ?? {}).map((cfg) => [cfg.styleKey, cfg.default]).filter(([, v]) => v !== undefined),
    ),
    contentOverrideSchema: {
      type: "object",
      required: ["key"],
      properties: {
        key: { type: "string", enum: keyEnum, description: `One of ${adapter.package}'s exported components.` },
      },
    },
    styleOverrideSchema: {
      type: "object",
      properties: { ...styleProps, width: { type: "number" }, height: { type: "number" } },
    },
  };
}

function buildComponent(adapter, exportNames) {
  const importLine = `import * as __lib from "${adapter.package}";`;
  const mapEntries = exportNames
    .map((n) => `  ${JSON.stringify(toContentKey(n, adapter.keyStrategy))}: __lib.${n} ?? __lib.default?.${n},`)
    .join("\n");
  const extraPropLines = Object.entries(adapter.extraProps ?? {})
    .map(([propName, cfg]) => `      ${propName}={resolvedStyle.${cfg.styleKey} ?? ${JSON.stringify(cfg.default)}}`)
    .join("\n");

  return `// GENERATED by src/registry/generateExternalAssetAdapters.js — do not hand-edit.
// Source: ${adapter.package}. Edit externalAdapters.config.js and regenerate instead.
import React from "react";
${importLine}

const __MAP = {
${mapEntries}
};

export function ${adapter.assetType}({ resolvedPosition, resolvedStyle, content }) {
  const Component = __MAP[content.key];
  if (!Component) {
    throw new Error(\`${adapter.assetType}: unknown key "\${content.key}". Known: \${Object.keys(__MAP).join(", ")}\`);
  }
  const width = resolvedStyle.width ?? ${adapter.defaultSize.width};
  const height = resolvedStyle.height ?? ${adapter.defaultSize.height};

  return (
    <div style={{ ...resolvedPosition, width, height }}>
      <Component
        ${adapter.sizeProp}={Math.min(width, height)}
        ${adapter.colorProp ? `${adapter.colorProp}={resolvedStyle.monoColor}` : ""}
${extraPropLines}
      />
    </div>
  );
}
`;
}

async function main() {
  for (const adapter of EXTERNAL_ADAPTERS) {
    const exportNames = await introspectExports(adapter.package);
    const manifest = buildManifest(adapter, exportNames);
    const outDir = path.join(ASSETS_ROOT, adapter.assetType);
    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(path.join(outDir, "manifest.json"), JSON.stringify(manifest, null, 2));
    fs.writeFileSync(path.join(outDir, `${adapter.assetType}.jsx`), buildComponent(adapter, exportNames));
    console.log(`Generated ${adapter.assetType}: ${exportNames.length} key(s) from "${adapter.package}"`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});